apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "spark.fullname" . }}-workers
  labels:
    app.kubernetes.io/name: {{ template "spark.name" . }}
    helm.sh/chart: {{ template "spark.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.workers }}
  strategy:
    type: RollingUpdate
  serviceName: {{ template "spark.fullname" . }}-workers
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "spark.name" . }}-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "spark.name" . }}-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ template "spark.fullname" . }}-worker
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        {{- range $key, $value := .Values.master.customEnv }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        args:
        - standalone
        - worker
        - --webui-port {{ .Values.worker.ui_port }}
        - --cores {{ .Values.worker.cores }}
        - spark://{{ template "spark.fullname" . }}:7077


      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
